apiVersion: apps/v1
kind: Deployment
metadata:
  name: simple-app-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: simple-app
  template:
    metadata:
      labels:
        app: simple-app
    spec:
      containers:
        - name: simple-app
          # Image will be dynamically updated in the pipeline
          image: ${REGISTRY_URL}/${IMAGE_NAME}:${IMAGE_TAG} 
          ports:
            - containerPort: 80
