apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: simple-app-hpa
  labels:
    app: simple-app
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: simple-app-deployment
  minReplicas: 2
  maxReplicas: 10
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 50  # Scale when CPU usage exceeds 50%
