apiVersion: apps/v1
kind: Deployment
metadata:
  name: datadog-cluster-agent
  namespace: datadog
spec:
  replicas: 1
  selector:
    matchLabels:
      app: datadog-cluster-agent
  template:
    metadata:
      labels:
        app: datadog-cluster-agent
    spec:
      containers:
      - name: cluster-agent
        image: datadog/cluster-agent:latest
        env:
        - name: DD_API_KEY
          value: "<YOUR_DATADOG_API_KEY>"
        - name: DD_SITE
          value: "datadoghq.com"
